Function with test of snake to camelCase added
Intelimetrica/botas pull request #8
Opened 2018-09-10 18:00 UTC by danz1295

2018-09-12 15:24 UTC, uquintana commented on source/utilities/formatters/index.js
> +      word  => word.split('_'),
There is an extra tab here

2018-09-12 15:24 UTC, uquintana commented
@Rantelo the documentation should be updated on this PR?

2018-09-13 22:33 UTC, Rantelo commented on source/utilities/formatters/index.js
> +  * snakeToCamelCase('snake_case_string', true): //=> 'SnakeCaseString'
Colons here should be semicolons

2018-09-14 03:12 UTC, Rantelo requested changes

2018-09-14 03:12 UTC, Rantelo commented on source/utilities/formatters/index.js
> +const snakeToCamelCase = (value, first_letter=false) => {
I suggest changing `first_letter` variable to `pascal_case` as described in [here](http://wiki.c2.com/?PascalCase)
- [x] change first_letter variable

2018-09-14 03:12 UTC, Rantelo commented on source/utilities/formatters/index.js
> +      words => words.map((w, index) => !first_letter && index == 0 ? w.toLowerCase() : capitalize(w.toLowerCase())),
I suggest separating `words => words.map((w, index) => !first_letter && index == 0 ? w.toLowerCase() : capitalize(w.toLowerCase()))` in two functions as:

```  
[
  word  => word.split('_'),
  words => words.map(w => capitalize(w)),
  words => { if (first_letter) { words[0].toLowerCase() }},
  words => words.join('')
];
```
Notice that there is no need to `lowerCase` what is inside `capitalize`

2018-09-14 03:12 UTC, Rantelo commented on source/utilities/formatters/test.js
> +    });
Could you add some other test cases? For example

- [ ] Throw an exception if the intended text starts with invalid (invalid to use as variable) characters as *^%-... or numbers
- [ ] Throw an exception if the intended text contains in between invalid characters (invalid to use as variable) such as *^%-({...

You can base the development of this functionality with [this article](https://mathiasbynens.be/notes/javascript-identifiers) and test it with [this site](https://mothereff.in/js-variables#yea)
Regex will be your friend.

2018-09-19 17:40 UTC, danz1295 commented on source/utilities/formatters/index.js
> +const isVarNameValid = (value) => {
This function will also be used in camelCaseToSnake function, but I'm not sure if this is a good place to put it, what do you think @Rantelo?

2018-09-19 22:44 UTC, Rantelo commented on source/utilities/formatters/index.js
> +const isVarNameValid = (value) => {
Great!
This is the type of validation I was expecting.
Can you create a new folder inside source named `constants` and add a file named `validVarName` which exports the regex by default?
It would look something like:
```
/* source/constants/validVarName.js */
export default new RegExp(/^(?!.....);
```

2018-09-19 22:44 UTC, Rantelo commented on source/utilities/formatters/index.js
> +const isVarNameValid = (value) => {
Can you also change `isVarNameValid` to `isValidVarName` and move it to `general`?

- [x] chnage var name and move it to general

2018-09-19 23:14 UTC, danz1295 commented on source/utilities/formatters/index.js
> +const isVarNameValid = (value) => {
The configuration in babel for "export default..." is missing

2018-09-20 00:30 UTC, uquintana approved these changes

2018-09-20 00:30 UTC, Rantelo approved these changes

2018-09-20 00:30 UTC, Rantelo commented on source/utilities/formatters/index.js
> +  snakeToCamelCase
Can you sort alphabetically the content of `module.exports`

2018-09-20 00:30 UTC, Rantelo commented on source/utilities/formatters/test.js
>    it('formatters exports a fixed number of functions', () => {
Can you add the new method in the comment at the beginning of this file?

2018-09-20 00:30 UTC, merged